#pragma once

#include "config.h"

#define HANDHELD_DOCK_PIXEL_RATIO 2 / 3
#define DOCK_HANDHELD_PIXEL_RATIO 3 / 2

// preprocess the demensions after scaling
#define LAYER_INFO_DOCKED_WIDTH OVERLAY_BASE_WIDTH_DOCKED * OVERLAY_UPSCALE_DOCKED
#define LAYER_INFO_DOCKED_HEIGHT OVERLAY_BASE_HEIGHT_DOCKED * OVERLAY_UPSCALE_DOCKED

#define LAYER_INFO_HANDHELD_WIDTH OVERLAY_BASE_WIDTH_HANDHELD * OVERLAY_UPSCALE_HANDHELD * HANDHELD_DOCK_PIXEL_RATIO
#define LAYER_INFO_HANDHELD_HEIGHT OVERLAY_BASE_HEIGHT_HANDHELD * OVERLAY_UPSCALE_HANDHELD * HANDHELD_DOCK_PIXEL_RATIO

// depending on the configuration, use the larger size for buffer
#define DOCKED_DOTS_TOTAL LAYER_INFO_DOCKED_WIDTH * LAYER_INFO_DOCKED_HEIGHT
#define HANDHELD_DOTS_TOTAL LAYER_INFO_HANDHELD_WIDTH * LAYER_INFO_HANDHELD_HEIGHT

#if DOCKED_DOTS_TOTAL > HANDHELD_DOTS_TOTAL
#    define LAYER_BUFFER_WIDTH LAYER_INFO_DOCKED_WIDTH
#    define LAYER_BUFFER_HEIGHT LAYER_INFO_DOCKED_HEIGHT
#    define LAYER_BUFFER_SIZE DOCKED_DOTS_TOTAL
#else
#    define LAYER_BUFFER_WIDTH LAYER_INFO_HANDHELD_WIDTH
#    define LAYER_BUFFER_HEIGHT LAYER_INFO_HANDHELD_HEIGHT
#    define LAYER_BUFFER_SIZE HANDHELD_DOTS_TOTAL
#endif
